# Generated by Django 3.2 on 2022-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_us', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('phone_number', models.TextField(max_length=100)),
                ('subtitle', models.CharField(max_length=30)),
                ('tw_link', models.URLField()),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='company/')),
                ('email_us', models.CharField(max_length=30)),
            ],
        ),
    ]
